stages:
- build
- test

build_job:
  stage: build
  script:
  - mkdir cmake-build-release && cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make && make install

test_job:
  stage: test
  script:
  - mkdir cmake-build-release && cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make && make install
  - ./test_indexmanager
  - ./test_casmanager